version: "3.7"

services:
  db:
    image: mariadb
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"

volumes:
  mariadb-data: