version: "3.7"

services:
  db:
    image: mariadb
    container_name: mariadb_container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: my-password
      MYSQL_DATABASE: bd-ventas
      MYSQL_USER: admin-ventas
      MYSQL_PASSWORD: my-secret-pw
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  mariadb-data: